version: "3.2"
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable # 2024.1.5
    environment:
      - TZ=Australia/Perth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /ocean/active/services/homeassistant:/config
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_a49962d47e45ed11a3dac68f0a86e0b4-if00-port0:/dev/ttyUSB0 # zigbee controller
    restart: unless-stopped
    privileged: true
    network_mode: host
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest # release-4.0.1.929
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 20010:8989
    environment:
      - PUID=2001
      - PGID=2001
      - TZ=Australia/Perth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /ocean/active/services/sonarr:/config
      - /ocean/active:/ocean/active
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:release # release-5.2.6.8376
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 20020:7878
    environment:
      - PUID=2002
      - PGID=2002
      - TZ=Australia/Perth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /ocean/active/services/radarr:/config
      - /ocean/active:/ocean/active
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr # 6.0.2
    container_name: recyclarr
    user: 2003:2003
    restart: unless-stopped
    environment:
      - TZ=Australia/Perth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /ocean/active/services/recyclarr:/config
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr # release-1.12.2.4211
    restart: unless-stopped
    ports:
      - "20040:9696"
    environment:
      - PUID=2004
      - PGID=2004
      - TZ=Australia/Perth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /ocean/active/services/prowlarr:/config
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest # release-1.4.0
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 20050:6767
    environment:
      - PUID=2005
      - PGID=2005
      - TZ=Australia/Perth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /ocean/active/services/bazarr:/config
      - /ocean/active:/ocean/active
  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 20060:8191
    environment:
      - PUID=2006
      - PGID=2006
      - TZ=Australia/Perth
      - LOG_LEVEL=info
  synclounge:
    container_name: synclounge
    image: synclounge/synclounge:latest
    user: 2008:2008
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 20080:8088
    environment:
      - TZ=Australia/Perth
  gtnh:
    # build:
    #   context: gtnh
    #   dockerfile: Dockerfile
    #   args:
    #     - PUID=2009
    #     - PGID=2009
    # container_name: gtnh-server
    # ports:
    #   - 25565:25565
    # volumes:
    #   - /ocean/active/services/gtnh/world:/data/World
    #   - /ocean/active/services/gtnh/world:/data/config
    #   - /ocean/active/services/gtnh/logs:/data/logs
    # tty: true
    # stdin_open: true
    # restart: unless-stopped
    container_name: gtnh
    image: itzg/minecraft-server:java21-alpine
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      - SETUP_ONLY=false

      - TYPE=CUSTOM
      - CUSTOM_SERVER=/data/lwjgl3ify-forgePatches.jar
      - VERSION=1.7.10
      - MOTD=GTNH Shouse
      - DIFFICULTY=2
      - LEVEL_TYPE=RTG
      - SEED=
      - JVM_OPTS=-Dfml.readTimeout=180 @java9args.txt

      - INIT_MEMORY=6G
      - MAX_MEMORY=8G
      - ENABLE_AUTOPAUSE=true
      - AUTOPAUSE_TIMEOUT_EST=300
      - AUTOPAUSE_TIMEOUT_INIT=60
      - VIEW_DISTANCE=14

      - UID=2009
      - GID=2009
      - TZ=Australia/Perth
      - EULA=true
      - ONLINE_MODE=true
      - ALLOW_FLIGHT=true
      - ENFORCE_WHITELIST=true
      - MAX_PLAYERS=5
      - OVERRIDE_SERVER_PROPERTIES=true
      - MAX_TICK_TIME=-1
    volumes:
      - /ocean/active/services/gtnh:/data
  monifactory:
    image: itzg/minecraft-server:java21-alpine
    restart: unless-stopped
    ports:
      - 25566:25565
    volumes:
      - /ocean/active/services/monifactory:/data
    environment:
      EULA: true
      TYPE: FORGE
      VERSION: 1.20.1
      FORGE_VERSION: 47.3.10
      GENERIC_PACK: "https://github.com/ThePansmith/Monifactory/releases/download/0.9.10/Monifactory-Beta.0.9.10-server.zip"
      UID: 2009
      GID: 2009
      TZ: Australia/Perth
      MEMORY: 8G
      USE_AIKAR_FLAGS: true
      WHITELIST: ariashark,shuppyy
      EXISTING_WHITELIST_FILE: MERGE
      OPS: ariashark,shuppyy
      EXISTING_OPS_FILE: MERGE
      MAX_PLAYERS: 5
      ALLOW_FLIGHT: true
      DIFFICULTY: peaceful
      MOTD: sharkuppy (ao!)
