version: "3.2"
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable # 2023.11.3
    environment:
      - TZ=Australia/Perth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /ocean/active/services/homeassistant:/config
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_a49962d47e45ed11a3dac68f0a86e0b4-if00-port0:/dev/ttyUSB0 # zigbee controller
    restart: unless-stopped
    privileged: true
    network_mode: host
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:nightly # 4.0.0.733
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 20010:8989
    environment:
      - PUID=2001
      - PGID=2001
      - TZ=Australia/Perth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /ocean/active/services/sonarr:/config
      - /ocean/active:/ocean/active
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:release # 5.1.3.8246
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 20020:7878
    environment:
      - PUID=2002
      - PGID=2002
      - TZ=Australia/Perth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /ocean/active/services/radarr:/config
      - /ocean/active:/ocean/active
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr # 6.0.2
    container_name: recyclarr
    user: 2003:2003
    environment:
      - TZ=Australia/Perth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /ocean/active/services/recyclarr:/config
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - "20040:9696"
    environment:
      - PUID=2004
      - PGID=2004
      - TZ=Australia/Perth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /ocean/active/services/prowlarr:/config
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 20050:6767
    environment:
      - PUID=2005
      - PGID=2005
      - TZ=Australia/Perth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /ocean/active/services/bazarr:/config
      - /ocean/active:/ocean/active
