# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "cuffs/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "cuffs/home";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "cuffs/nix";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5F26-EADC";
      fsType = "vfat";
    };

  swapDevices =
    [
{
device = "/dev/disk/by-partuuid/21e8f50c-60ac-4b44-b046-0bc6ae167a35";
randomEncryption = {
enable = true;
cipher = "aes-xts-plain64";
source = "/dev/random";
};
}
    ];

  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
