# https://github.com/plexinc/pms-docker/blob/c7dd9df342c5b998042cae75179e24dd8f887630/docker-compose-host.yml.template
# https://github.com/plexinc/pms-docker/blob/c7dd9df342c5b998042cae75179e24dd8f887630/README.md#parameters
version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker #
    restart: unless-stopped
    environment:
      - TZ=Australia/Perth
      - PLEX_UID=2101
      - PLEX_GID=2101
    network_mode: host
    hostname: plex.daz.cat
    volumes:
      - /cuffs/plex/config:/config
      - /cuffs/plex/transcode:/transcode
      - /ocean/active/sonarr:/sonarr
      - /ocean/active/radarr:/radarr
      - /ocean/active/plex/videos:/videos
    devices:
      - /dev/dri:/dev/dri
